spring:
  application:
    name: securitydemo
  security:
    user:
      name: admin
      password: demo123
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test

  app:
    jwtSecret: dictionary2224324uifbhfiuhbfud8958t948tihiuvhsudAHJDHJFJFNFJNJJJIJrigroeigurooisdjvdlnvjdnfkjsdhfiuehdfuidh
    jwtExpirationMS: 6000000000

logging:
  level:
    org:
      springframework: DEBUG
      springframework.security: DEBUG
      hibernate:
        sql: DEBUG
    com:
      example:
        securitydemo: DEBUG