spring:
  application:
    name: securitydemo
  security:
    user:
      name: admin
      password: demo123
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test