server:
  port: 8080

spring:
  application:
    name: e-commerce-application

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username:
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  app:
    jwtSecret: dictionary2224324uifbhfiuhbfud8958t948tihiuvhsudAHJDHJFJFNFJNJJJIJrigroeigurooisdjvdlnvjdnfkjsdhfiuehdfuidh
    jwtExpirationMS: 6000000000

logging:
  level:
    org:
      springframework: DEBUG
      springframework.security: DEBUG
      hibernate:
        sql: DEBUG
    com:
      ecommerce:
        app: DEBUG

project:
  image: images/

