server:
  port: 8080

spring:
  application:
    name: e-commerce-application

  datasource:
    url: jdbc:mysql://localhost:3306/e-commerce
    #    driver-class-name:
    username: root
    password: root

  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2-console

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  app:
    jwtSecret: dictionary2224324uifbhfiuhbfud8958t948tihiuvhsudAHJDHJFJFNFJNJJJIJrigroeigurooisdjvdlnvjdnfkjsdhfiuehdfuidh
    jwtExpirationMS: 6000000000
    jwtCookieName: springbootEcom

logging:
  level:
    org:
      springframework: DEBUG
      springframework.security: DEBUG
      hibernate:
        sql: DEBUG
    com:
      ecommerce:
        app: DEBUG

project:
  image: images/

